Repository deptofdefense/solo, pull requests merged in 2020-01, with the labels that each got.

#19 Create an issue template for research questions
  .github/ISSUE_TEMPLATE/RESEARCH_TEMPLATE
  .gitignore
  CONTRIBUTORS.md
Labels: documentation

#8 update signed-off-by and gitignore
  .gitignore
  CONTRIBUTORS.md
Labels: documentation

#21 Add .md extension to research issue template and lowercase the filename
  .github/ISSUE_TEMPLATE/research_template.md
Labels: documentation

#26 Issue#18 Create Hello World Front-end React App
  .gitignore
  frontend/.dockerignore
  frontend/.eslintrc.json
  frontend/Dockerfile
  frontend/README.md
  frontend/nginx.conf
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/public/manifest.json
  frontend/public/robots.txt
  frontend/src/App.tsx
  frontend/src/__tests__/components/app.spec.tsx
  frontend/src/__tests__/components/banner.spec.tsx
  frontend/src/components/Banner.tsx
  frontend/src/index.tsx
  frontend/src/react-app-env.d.ts
  frontend/src/serviceWorker.ts
  frontend/src/setupTests.ts
  frontend/tsconfig.json
Labels: enhancement

#36 #27 Added CircleCI Configuration for Typechecking, Linting, and Testing the Frontend
  .circleci/config.yml
Labels: enhancement

#32 #20 Create Hello World Back-end Django App
  .gitignore
  backend/.pylintrc
  backend/Dockerfile
  backend/README.md
  backend/__init__.py
  backend/app/__init__.py
  backend/app/settings.py
  backend/app/urls.py
  backend/app/wsgi.py
  backend/manage.py
  backend/requirements/requirements.dev.txt
  backend/requirements/requirements.txt
  backend/solo_rog_api/__init__.py
  backend/solo_rog_api/admin.py
  backend/solo_rog_api/apps.py
  backend/solo_rog_api/migrations/__init__.py
  backend/solo_rog_api/models.py
  backend/solo_rog_api/test/__init__.py
  backend/solo_rog_api/test/tests.py
  backend/solo_rog_api/views.py
Labels: enhancement

#43 Run 'black .' to fix code style error
  backend/app/settings.py
  backend/solo_rog_api/test/tests.py
Labels: bug

#46 Cache dependencies in CI/CD pipeline
  .circleci/config.yml
Labels: enhancement

#53 Feat 50 Configure tests to collect code coverage
  .gitignore
  backend/.coveragerc
  backend/README.md
  backend/requirements/requirements.dev.txt
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
Labels: enhancement

#65 Delete bug line on feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: bug

#66 Added test coverage checks to CI/CD pipeline.
  .circleci/config.yml
Labels: build

#67 Feat 52 pipeline static analysis (Bandit)
  .circleci/config.yml
  backend/requirements/requirements.dev.txt
Labels: build

#56 Feat 55 add a pre-commit hook with usage instructions
  CONTRIBUTING.md
  hooks/precommit.sh
Labels: app feature

#70 Update PULL_REQUEST_TEMPLATE.md
  .circleci/config.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: build, documentation
