Repository deptofdefense/solo, pull requests merged in 2020-02, with the labels that each got.

#69 create initial api endpoint to test
  .gitignore
  backend/.pylintrc
  backend/app/settings.py
  backend/app/urls.py
  backend/pyproject.toml
  backend/solo_rog_api/admin.py
  backend/solo_rog_api/migrations/0001_initial.py
  backend/solo_rog_api/models.py
  backend/solo_rog_api/serializers.py
  backend/solo_rog_api/test/test_log.py
  backend/solo_rog_api/test/tests.py
  backend/solo_rog_api/urls.py
  backend/solo_rog_api/views.py
Labels: LOE 2, app feature

#72 Feat 24 incorporate uswds
  .gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/__tests__/components/app.spec.tsx
  frontend/src/__tests__/components/banner.spec.tsx
  frontend/src/components/Banner.tsx
  frontend/src/components/Header/Header.tsx
  frontend/src/components/Header/HeaderLogo.tsx
  frontend/src/components/Header/HeaderNav.tsx
  frontend/src/components/Header/HeaderNavLink.tsx
  frontend/src/components/Header/__tests__/__snapshots__/header.spec.tsx.snap
  frontend/src/components/Header/__tests__/header.spec.tsx
  frontend/src/components/Header/index.ts
  frontend/src/components/Layout/Layout.tsx
  frontend/src/components/Layout/__tests__/layout.spec.tsx
  frontend/src/components/Layout/index.ts
  frontend/src/components/OfficialSiteBanner/OfficialSiteBanner.tsx
  frontend/src/components/OfficialSiteBanner/__tests__/__snapshots__/officialSiteBanner.spec.tsx.snap
  frontend/src/components/OfficialSiteBanner/__tests__/officialSiteBanner.spec.tsx
  frontend/src/components/OfficialSiteBanner/index.ts
  frontend/src/styles.scss
  frontend/src/test-utils.tsx
  frontend/tsconfig.json
Labels: app feature

#88 Remove snyk from CI pipeline in favor of connecting directly to GitHub repo
  .circleci/config.yml
Labels: build

#87 update readme with circlci status badge and dod vdp
  README.md
Labels: documentation

#90 Remediation to SQL Injection Vulnerability Identified by SNYK
  backend/requirements/requirements.txt
Labels: dependencies

#92 bump react-scripts to latest version in response to medium level snyk…
  frontend/package-lock.json
  frontend/package.json
Labels: dependencies

#86 Feat 76 Configure development environment / proxy API calls to backend
  .gitignore
  CONTRIBUTING.md
  backend/Dockerfile
  backend/app/settings.py
  backend/requirements/requirements.txt
  deploy/compose/.env.example
  deploy/compose/docker-compose.override.yml
  deploy/compose/docker-compose.yml
  frontend/Dockerfile
  frontend/nginx/entrypoint.sh
  frontend/nginx/nginx.template
  frontend/nginx/snippets/client-ca-bundle.pem
  frontend/nginx/snippets/ssh-params.conf
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/__tests__/root.spec.ts
  frontend/src/api/auth.ts
  frontend/src/api/index.ts
  frontend/src/api/root.ts
  frontend/src/components/HomePage/HomePage.module.css
  frontend/src/components/HomePage/HomePage.tsx
  frontend/src/components/HomePage/__tests__/__snapshots__/homePage.spec.tsx.snap
  frontend/src/components/HomePage/__tests__/homePage.spec.tsx
  frontend/src/components/HomePage/index.ts
  frontend/src/components/Layout/Layout.tsx
  frontend/src/components/Layout/__tests__/layout.spec.tsx
  frontend/src/components/LoginButton/LoginButton.module.css
  frontend/src/components/LoginButton/LoginButton.tsx
  frontend/src/components/LoginButton/__tests__/__snapshots__/loginButton.spec.tsx.snap
  frontend/src/components/LoginButton/__tests__/loginButton.spec.tsx
  frontend/src/components/LoginButton/index.ts
  frontend/src/styles.scss
Labels: app feature

#96 Feat 77 jwt generation
  .circleci/config.yml
  backend/.coveragerc
  backend/.pylintrc
  backend/Dockerfile
  backend/app/settings.py
  backend/manage.py
  backend/mypy.ini
  backend/requirements/requirements.dev.txt
  backend/requirements/requirements.txt
  backend/solo_rog_api/authentication.py
  backend/solo_rog_api/migrations/0001_initial.py
  backend/solo_rog_api/models.py
  backend/solo_rog_api/serializers.py
  backend/solo_rog_api/test/test_authentication_backend.py
  backend/solo_rog_api/test/test_log.py
  backend/solo_rog_api/test/test_serializers.py
  backend/solo_rog_api/test/test_views.py
  backend/solo_rog_api/urls.py
  backend/solo_rog_api/views.py
  deploy/compose/docker-compose.override.yml
  deploy/compose/docker-compose.yml
  frontend/Dockerfile
  frontend/nginx/entrypoint.sh
  frontend/nginx/nginx.template
  frontend/src/api/auth.ts
  frontend/src/api/root.ts
  frontend/src/components/HomePage/HomePage.tsx
  frontend/src/components/HomePage/__tests__/homePage.spec.tsx
  hooks/precommit.sh
Labels: app feature

#100 #83 Initial aws infrastructure creation
  .gitignore
  deploy/staging/infrastructure/README.MD
  deploy/staging/infrastructure/infrastructure-stage.config
  deploy/staging/infrastructure/infrastructure-stage.tfvars
  deploy/staging/infrastructure/outputs.tf
  deploy/staging/infrastructure/variables.tf
  deploy/staging/infrastructure/vpc.tf
Labels: infrastructure

#101 #99 initial aws platform creation
  deploy/staging/platform/README.MD
  deploy/staging/platform/ecs.tf
  deploy/staging/platform/outputs.tf
  deploy/staging/platform/platform-stage.config
  deploy/staging/platform/platform-stage.tfvars
  deploy/staging/platform/variables.tf
Labels: infrastructure

#102 #82 initial aws application creation
  deploy/staging/application/README.MD
  deploy/staging/application/app.tf
  deploy/staging/application/application-stage.config
  deploy/staging/application/application-stage.tfvars
  deploy/staging/application/container_definition.json
  deploy/staging/application/outputs.tf
  deploy/staging/application/variables.tf
Labels: infrastructure

#109 Feat 98 Development Authentication
  backend/app/settings.py
  backend/solo_rog_api/authentication.py
  backend/solo_rog_api/test/test_authentication_backend.py
  deploy/compose/docker-compose.override.yml
  deploy/compose/docker-compose.yml
  frontend/src/context/AuthContextProvider.tsx
  frontend/src/context/__tests__/authContext.spec.tsx
Labels: development-tool

#118 Fixed local HTTPS/CAC Authentication to work with the Terraform AWS Deployment Changes
  .gitignore
  CONTRIBUTING.md
  deploy/compose/.env.example
  deploy/compose/configure-local-environment.sh
  deploy/compose/docker-compose.yml
Labels: development-tool
